# Generated by Django 3.2.8 on 2021-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='uhuy',
        ),
    ]
