# Generated by Django 3.2.8 on 2021-10-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_minuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='minuman',
        ),
    ]
